app:
  pageImageRoot: /data/metseditor/pageImage
  solrUrl: http://localhost:8983/solr/volume
---
grails:
    profile: org.grails.profiles:zk:1.0.1
    codegen:
        defaultPackage: metseditor
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugin:
        springsecurity:
            logout:
                postOnly: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            png: image/png
            jpg: image/jpeg
            jpeg: image/jpeg
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
#            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            url: jdbc:mysql://localhost:3306/grails?useSSL=false&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: metseditor
            password: QUoo7pLbs348KR

    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

    production:
        dataSource:
            pooled: true
            dbCreate: update
            url: jdbc:mysql://localhost:3306/metseditor?useSSL=false&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: metseditor
            password: QUoo7pLbs348KR
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 10 * 60000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                ignoreExceptionOnPreLoad: true
                jdbcInterceptors: ConnectionState;StatementCache(max=200)
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
                abandonWhenPercentageFull: 100
                removeAbandonedTimeout: 120
                removeAbandoned: true
                logAbandoned: false
                dbProperties:
                    autoReconnect: false
                    jdbcCompliantTruncation: false
                    zeroDateTimeBehavior: convertToNull
                    cachePrepStmts: false
                    cacheCallableStmts: false
                    dontTrackOpenResources: true
                    holdResultsOpenOverStatementClose: true
                    useServerPrepStmts: false
                    cacheServerConfiguration: true
                    cacheResultSetMetadata: true
                    metadataCacheSize: 100
                    connectTimeout: 15000
                    socketTimeout: 120000
                    maintainTimeStats: false
                    enableQueryTimeouts: false
                    noDatetimeStringSync: true
server:
    contextPath: /MetsEditor